#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
ITERM_DIR="${0:A:h}/config"

# only for macOS
[[ $(_os) != macos ]] && exit

install() {
  brew cask install iterm2

  # Enable italics
  tic xterm-256color.terminfo

  # Specify the preferences directory
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$ITERM_DIR"
  # Tell iTerm2 to use the custom preferences in the directory
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
  # Don’t display the annoying prompt when quitting iTerm
  defaults write com.googlecode.iterm2 PromptOnQuit -bool false
}

# update() {}

# link() {}

clean() {
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool false
}

init "$@"
