#!/usr/bin/env bash

deps=(
  git
  bash
  bash-completion
  zsh
  fasd
)

if pop-and-missing fasd apt; then
  sudo add-apt-repository ppa:aacebedo/fasd
  sudo apt-get update
fi

install-deps
stow-module

if [[ "$PACKAGE_MANAGER" == "brew" ]]; then
  # Add homebrewed zsh to /etc/shells
  if ! grep '/usr/local/bin/zsh' /etc/shells >/dev/null; then
    sudo tee -a /etc/shells <<< "/usr/local/bin/zsh"
  fi

  # Don't mess with my PATH!
  echo "Disable /etc/zprofile and /etc/profile as they mess with my PATH!"
  [[ -f /etc/zprofile ]] && sudo mv /etc/zprofile /etc/zprofile.disabled
  [[ -f /etc/profile ]] && sudo mv /etc/profile /etc/profile.disabled
fi

# set default shell if it's not already done
if [[ $SHELL =~ zsh ]]; then
  echo "You are already running a zsh shell, Good for you!"
else
  _zsh_path="$(command -v zsh)"

  echo "It's time to change your default shell to ZSH..."
  sudo chsh -s "${_zsh_path}" "$(whoami)"
  echo "Reloading shell to apply changes."
  echo "Once the reload it's done, do not forget to compile zplugin and its plugins:"
  echo ""
  echo "    zplugin compile --all"
  echo "    zcompile ~/.zplugin/bin/zplugin.zsh"
  exec "$_zsh_path" -l
fi
