#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

brew_deps_with_args=(
  'findutils --with-default-names'
  'gnu-sed --with-default-names'
  'grep --with-default-names'
  'wget --with-iri'
)

brew_deps=(
  openssh
  rsync
  openssl
  mvtools
  ffms2
  subliminal
  highlight
  htop
  gtypist
  pgcli
  p7zip
  unzip
  unrar
  android-platform-tools
)

cask_deps=(
  1password
  adobe-reader
  alfred
  android-file-transfer
  appcleaner
  betterzipql
  borgbackup
  calibre
  firefox
  flux
  google-chrome
  google-chrome-canary
  google-drive
  grandperspective
  handbrake
  java
  jdownloader
  keka
  keycastr
  licecap
  mpv
  omnidisksweeper
  opera
  postico
  qlcolorcode
  qlimagesize
  qlmarkdown
  qlprettypatch
  qlstephen
  quicklook-json
  screenhero
  skype
  slack
  spotify
  sshfs
  torbrowser
  transmission
  unetbootin
  virtualbox
  vlc
  wireshark
)

install() {
  case $(_os) in
    macos)
      brew install ${brew_deps[@]}
      for pkg ($brew_deps_with_args) brew install $pkg
      brew cask install ${cask_deps[@]}
      ;;
  esac
}

# update() {}

# link() {}

# clean() {}

init "$@"
