#!/usr/bin/env bash

basedeps=(git)
deps=(hub)

if pop-and-missing hub apt; then
  mkdir -p "$HOME"/builds && cd "$HOME"/builds
  git clone https://github.com/github/hub.git && cd hub
  make install prefix=/usr/local
fi

install-deps
stow-module
