#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

# install() {}

# update() {}

link() {
  mklink surfingkeys.js $XDG_CONFIG_HOME

  echo
  echo-note "To complete the setup you will need to do the following in Chrome:"
  echo "- Allow cvim access to file URLs through Chrome's extension settings"
  echo "- Check option 'Advanced mode'"
  echo "- Paste full path of the local settings file in the input:"
  echo -n "$(tput bold)"
  echo "  $XDG_CONFIG_HOME/surfingkeys.js"
  echo -n "$(tput sgr0)"
  echo "- Click Save"
  echo
}

clean() {
  rm -fv "$XDG_CONFIG_HOME/surfingkeys.js"
}

init "$@"
