(require 'key-chord)

(key-chord-define-global ";;" 'switch-to-previous-buffer)
(key-chord-define-global ";b" 'ido-switch-buffer)
;(key-chord-define-global ";r" 'recentf-ido-find-file)
(key-chord-define-global ";f" 'ido-find-file)
(key-chord-define-global ";g" 'magit-status)
;(key-chord-define-global ";m" 'ace-jump-mode)
;(key-chord-define-global ";c" 'hemacs-todo-capture)
;(key-chord-define-global ";t" 'hemacs-goto-todos)
(key-chord-define-global ";o" 'magit-in-perspective)
;(key-chord-define-global ";s" 'persp-switch)
;(key-chord-define-global ";l" 'persp-shell)
(key-chord-define-global ";d" 'dired-jump)
;(key-chord-define-global ";a" 'ack-and-a-half)

(key-chord-mode +1)
