#!/usr/bin/env bash

if [[ "$PACKAGE_MANAGER" == "brew" ]]; then
  cask_deps=(
    font-hack
    font-fira-code
    font-fira-mono
    font-fira-sans
    font-dejavu-sans
  )

  brew tap caskroom/fonts
  brew cask install ${cask_deps[@]}
fi
