#!/usr/bin/env bash

source "$HOME/.dotfiles/lib/init-gpg-agent"

# # force 256-color gruvbox palette
# # https://github.com/morhetz/gruvbox-generalized/tree/master/iterm2
# source_file "$HOME/.dotfiles/vim/plugged/gruvbox/gruvbox_256palette_osx.sh"


####################################################################################
# Node version manager                                                             #
####################################################################################
source_file "/usr/local/opt/nvm/nvm.sh"


####################################################################################
# FASD                                                                             #
####################################################################################
fasd_cache=$HOME/.fasd-init-$SHELL_NAME
if type_exists 'fasd'; then
  if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
    if [ $IS_ZSH ]; then
      fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
    elif [ $IS_BASH ]; then
      fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install >| "$fasd_cache"
    fi
  fi
fi
source_file "$fasd_cache"
unset fasd_cache


####################################################################################
# FZF                                                                              #
####################################################################################
[[ $- == *i* ]] && source_file ${BREW_LOCATION}/opt/fzf/shell/completion.${SHELL_NAME}
source_file ${BREW_LOCATION}/opt/fzf/shell/key-bindings.${SHELL_NAME}


####################################################################################
# Chruby                                                                           #
####################################################################################
source_file $BREW_LOCATION/opt/chruby/share/chruby/chruby.sh

# Enable auto-switching of Rubies specified by .ruby-version files
source_file $BREW_LOCATION/opt/chruby/share/chruby/auto.sh
# type_exists chruby && test "$(chruby | grep ruby)" && chruby ruby

####################################################################################
# TheFuck                                                                          #
####################################################################################
if type_exists 'thefuck'; then
  eval "$(thefuck --alias)"
fi
