#!/usr/bin/env bash

if [[ -n $ZSH_VERSION ]]; then
  IS_ZSH=1
  SHELL_NAME="zsh"
elif [[ -n $BASH_VERSION ]]; then
  IS_BASH=1
  SHELL_NAME="bash"
fi

source "$HOME/.dotfiles/lib/init-gpg-agent"

# # force 256-color gruvbox palette
# # https://github.com/morhetz/gruvbox-generalized/tree/master/iterm2
# source_file "$HOME/.dotfiles/vim/plugged/gruvbox/gruvbox_256palette_osx.sh"


####################################################################################
# Node version manager                                                             #
####################################################################################
export NVM_DIR=${HOME}/.nvm
# TODO Make lazy_load compatible with bash
if [[ $IS_ZSH ]]; then
  lazy_source nvm $BREW_LOCATION/opt/nvm/nvm.sh
fi


####################################################################################
# FASD                                                                             #
####################################################################################
fasd_cache=$HOME/.fasd-init-$SHELL_NAME
if [ "$(type_exists fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  if [[ $IS_ZSH ]]; then
    fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
  elif [[ $IS_BASH ]]; then
    fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install >| "$fasd_cache"
  fi
fi
source "$fasd_cache"
unset fasd_cache


####################################################################################
# FZF                                                                              #
####################################################################################
export FZF_DEFAULT_OPTS="--extended --cycle"

# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='
  (git ls-tree -r --name-only HEAD ||
    ag -l -g "" ||
    find * -name ".*" -prune -o -type f -print -o -type l -print) 2> /dev/null'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND=${FZF_DEFAULT_COMMAND}

# Setup fzf
# ---------
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="$PATH:/usr/local/opt/fzf/bin"
fi

# Man path
# --------
if [[ ! "$MANPATH" == */usr/local/opt/fzf/man* && -d "/usr/local/opt/fzf/man" ]]; then
  export MANPATH="$MANPATH:/usr/local/opt/fzf/man"
fi

[[ $- == *i* ]] && source_file ${BREW_LOCATION}/opt/fzf/shell/completion.${SHELL_NAME}
source_file ${BREW_LOCATION}/opt/fzf/shell/key-bindings.${SHELL_NAME}


####################################################################################
# Chruby                                                                           #
####################################################################################
source_file $BREW_LOCATION/opt/chruby/share/chruby/chruby.sh

# Enable auto-switching of Rubies specified by .ruby-version files
source_file $BREW_LOCATION/opt/chruby/share/chruby/auto.sh
