#!/usr/bin/env bash
export DOT="$HOME/.dotfiles"

# Test whether a command exists
# $1 - cmd to test
type_exists() {
  # hash caches results but not works for all commands
  # hash $1 2>/dev/null
  command -v $1 >/dev/null
}

lazy_source () {
  eval "$1 () { [ -f $2 ] && source $2 && $1 \$@ }"
}

# source and evaluate a command if it is passed as second argument
source_file () {
  if [[ -s "$1" ]]; then
    source "$1"
  fi
}

source_and_eval () {
  if [[ -s "$1" ]]; then
    source "$1"
    test "$2" && type_exists "$2" && eval "$2"
  fi
}

# Header logging
e_header() {
  printf "\n$(tput setaf 7)%s$(tput sgr0)\n" "$@"
}

# Success logging
e_success() {
  printf "$(tput setaf 64)✓ %s$(tput sgr0)\n" "$@"
}

# Error logging
e_error() {
  printf "$(tput setaf 1)x %s$(tput sgr0)\n" "$@"
}

# Warning logging
e_warning() {
  printf "$(tput setaf 136)! %s$(tput sgr0)\n" "$@"
}

# Ask for confirmation before proceeding
seek_confirmation() {
  printf "\n"
  e_warning "$@"
  read -p "Continue? (y/n) " -n 1
  printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
is_confirmed() {
  [[ "$REPLY" =~ ^[Yy]$ ]] && return 0
  return 1
}

# Test whether a Homebrew formula is already installed
# $1 - formula name (may include options)
formula_exists() {
  test "$(brew list $1 2&>/dev/null)" && return 0
  return 1
}

if [[ -x "$(which brew)" ]]; then
  export HAS_BREW=1
  # BREW_LOCATION=`brew --prefix`
  export BREW_LOCATION="/usr/local"
fi
