#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

# Dependencies

common_deps=(
  the_silver_searcher
  ripgrep
  sqlite
)

brew_deps=(
  coreutils
  gnu-tar
  cmake
  llvm
)

cask_deps=(
  font-hack
  font-hack-nerd-font
  font-iosevka
  font-iosevka-nerd-font
)

install() {
  case $(_os) in
    macos)
      brew install ${common_deps[@]} ${brew_deps[@]}
      brew cask install ${cask_deps[@]}
      brew cask install emacs
      ;;
  esac

  # Clone and setup doom-emacs
  _ensure_repo eduarbo/doom-emacs ~/.emacs.d develop

  cd ~/.emacs.d && YES=1 make install
}

update() {
  cd ~/.emacs.d && YES=1 make update
}

link() {
  mklink doom $XDG_CONFIG_HOME
}

clean() {
  rm -rfv "$XDG_CONFIG_HOME/doom" "~/.emacs.d"
}

init "$@"
