#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
GIT_DIR="$XDG_CONFIG_HOME/git"

install() {
  case $(_os) in
    macos)  brew install git hub ;;
    arch)   pacaur --needed --noconfirm --noedit -S git hub ;;
    fedora) sudo dnf install -y git hub ;;
    debian)
      sudo apt-get install -y git
      # Install hub
      if [[ ! -e $XDG_BIN_HOME/hub ]]; then
        wget -O hub.tgz $(curl -s https://api.github.com/repos/github/hub/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep linux-amd64)
        tar xzvf hub.tgz && cd hub-linux-*(/) && cp bin/hub $XDG_BIN_HOME/hub
        wget -O $XDG_BIN_HOME/_hub https://raw.githubusercontent.com/github/hub/master/etc/hub.zsh_completion
      fi
  esac
}

# update() {}

link() {
  mklink {config,ignore} $GIT_DIR/
}

clean() {
  rm -rfv $GIT_DIR
}

init "$@"
