#!/usr/bin/env bash

brew_deps=(
  borgbackup
  'findutils --with-default-names'
  'gnu-sed --with-default-names'
  'grep --with-default-names'
  openssh
  rsync
  openssl
  mvtools
  ffms2
  subliminal
  highlight
  htop
  gtypist
  pgcli
  'wget --with-iri'
  p7zip
  unzip
  unrar
  tree
  screenfetch
  android-platform-tools
)

if pop-and-missing borgbackup brew; then
  brew tap caskroom/cask
  brew cask install borgbackup
fi

install-deps
