#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

# only for macOS
[[ $(_os) != macos ]] && exit

install() {
  if [[ $(_os) == macos ]]; then
    brew cask install karabiner-elements
  fi

  mkdir -p $KARABINER_COMPLEX_MODIFICATIONS
  sh lib/update-json.sh
  sh lib/apply-lint.sh
}

update() {
  sh lib/update-json.sh
  sh lib/apply-lint.sh
}

link() {
  mklink karabiner.json $KARABINER_DIR/
}

clean() {
  rm -fv $KARABINER_DIR $KARABINER_DATA_DIR
}

init "$@"
