#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

# only for macOS
[[ $(_os) != macos ]] && exit

install() {
  brew cask install karabiner-elements

  echo "INSTALL"
  mkdir -p $KARABINER_COMPLEX_MODIFICATIONS
  sh lib/update-json.sh
  sh lib/apply-lint.sh
}

update() {
  echo "UPDATE"
  sh lib/update-json.sh
  sh lib/apply-lint.sh
}

link() {
  echo "LINK"
  mklink config $KARABINER_DIR
}

clean() {
  rm -fv $KARABINER_DIR $KARABINER_DATA_DIR
}

init "$@"
