#!/usr/bin/env bash

if [[ "$PACKAGE_MANAGER" == "brew" ]]; then
  brew_deps=(
    python
    python3
    ipython
  )

  install-deps

  # Install virtualenv only in python2, for python3 we have the built-in venv module
  PIP_REQUIRE_VIRTUALENV="" pip2 install virtualenv

  # TODO: Install completions for pip and python
else
  echo "Unsupported OS"
fi
