#!/bin/sh

# Clean preferences
/Applications/Karabiner.app/Contents/Library/bin/karabiner \
     be_careful_to_use__clear_all_values_by_name \
     "Default Profile"

cli=/usr/local/bin/karabiner

$cli set option.emacsmode_ex_controlW 1
/bin/echo -n .
$cli set private.ctrl_hjkl_to_left_down_up_right 1
/bin/echo -n .
$cli set private.f19_to_delete 1
/bin/echo -n .
$cli set private.mega_hjkl_to_left_down_up_right 1
/bin/echo -n .
$cli set private.mega_to_command_shift_brackets 1
/bin/echo -n .
$cli set private.option_l_to_bracket_l 1
/bin/echo -n .
$cli set private.option_L_to_mega 1
/bin/echo -n .
$cli set private.option_r_to_bracket_r 1
/bin/echo -n .
$cli set private.option_r_to_escape 1
/bin/echo -n .
$cli set private.option_R_to_mega 1
/bin/echo -n .
$cli set private.shifts_to_parens 1
/bin/echo -n .
$cli set remap.command_to_command_brackets 1
/bin/echo -n .
$cli set remap.command_to_command_escape 1
/bin/echo -n .
$cli set remap.commandR2forwarddelete 1
/bin/echo -n .
$cli set remap.controlL2optionL 1
/bin/echo -n .
$cli set remap.delete2capslock 1
/bin/echo -n .
$cli set remap.doublepresscommandQ 1
/bin/echo -n .
$cli set remap.launcher_mode_v2 1
/bin/echo -n .
$cli set remap.space_to_control 1
/bin/echo -n .
$cli set repeat.initial_wait 250
/bin/echo -n .
$cli set repeat.wait 33
/bin/echo -n .
/bin/echo
