#!/bin/sh

# Clean preferences
/usr/local/bin/karabiner \
  be_careful_to_use__clear_all_values_by_name \
  "Default Profile"

/usr/local/bin/karabiner \
  be_careful_to_use__clear_all_values_by_name \
  "My Profile"

/usr/local/bin/karabiner \
  select_by_name "My Profile"

sh "$HOME/.dotfiles/karabiner/import.sh"
