#!/usr/bin/env bash

brew_deps=(iterm2)

case $OSTYPE in
  darwin*)
    brew tap caskroom/cask

    # Enable italics
    tic xterm-256color.terminfo

    # Specify the preferences directory
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DOTFILES/terminal"
    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
    ;;
  linux*)
    # TODO: Look for a nice terminal
    ;;
esac
