#!/usr/bin/env bash

if [[ "$PACKAGE_MANAGER" == "brew" ]]; then
  deps=(
    google-drive
    alfred
  )

  brew tap caskroom/cask
  brew cask install ${deps[@]}

  # Setup Alfred 2
  # disable spotlight on cmd-space so Alfred can use it
  defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 64 "{ enabled = 0; value = { parameters = ( 32, 49, 1048576); type = standard; }; }"
  # disable spotlight window shortcut
  defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 65 "{ enabled = 0; value = { parameters = ( 32, 49, 1048576); type = standard; }; }"
  # Alfred prefs
  defaults write com.runningwithcrayons.Alfred-Preferences-3 syncfolder -string "$HOME/Google Drive/prefs"
fi
