#!/usr/bin/env zsh
# Keep 9999 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=9999
SAVEHIST=9999
HISTFILE=~/.history

# setopt SHARE_HISTORY          # Shares history between all sessions
setopt BANG_HIST              # Treats the ! character specially during expansion
# Commented to keep compatibility with bash histfile
# setopt EXTENDED_HISTORY       # Writes the history file in the :start:elapsed;command format
setopt HIST_EXPIRE_DUPS_FIRST # Expires a duplicate event first when trimming history
setopt HIST_EXPIRE_DUPS_FIRST # Expires a duplicate event first when trimming history
setopt HIST_FIND_NO_DUPS      # Does not display a previously found event
setopt HIST_IGNORE_ALL_DUPS   # Deletes an old recorded event if a new event is a duplicate
setopt HIST_IGNORE_DUPS       # Does not record an event that was just recorded again
setopt HIST_IGNORE_SPACE      # Does not record an event starting with a space
setopt HIST_SAVE_NO_DUPS      # Does not write a duplicate event to the history file
setopt HIST_VERIFY            # Does not execute immediately upon history expansion
setopt INC_APPEND_HISTORY     # Writes to the history file immediately, not when the shell exits