#!/bin/zsh
if [ $HAS_BREW ]; then
  _brew_prefix="/usr/local"
  fpath=($_brew_prefix/share/zsh-completions $fpath)
  _files=(
  $_brew_prefix/etc/profile.d/z.sh
  $_brew_prefix/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  $_brew_prefix/opt/zsh-history-substring-search/zsh-history-substring-search.zsh
  )
  for file ($_files) [[ -f $file ]] && source $file
  unset _files _brew_prefix
fi

lazy_source () {
  eval "$1 () { [ -f $2 ] && source $2 && $1 \$@ }"
}

chrubyPath="/usr/local/share/chruby/chruby.sh"
if [[ -e $chrubyPath ]]; then
  source $chrubyPath
  chruby ruby
fi

# Rbenv
if (( $+commands[rbenv] )); then
  path=("$HOME/.rbenv/bin" $path)
  eval "$(rbenv init - --no-rehash zsh)"
fi

lazy_source nvm "$HOME/.nvm/nvm.sh"

# Automatic Version Manager for Node
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

# force 256-color gruvbox palette
# https://github.com/morhetz/gruvbox-generalized/tree/master/iterm2
GRUVBOX="$HOME/.dotfiles/vim/plugged/gruvbox/gruvbox_256palette_osx.sh"
[[ -e $GRUVBOX ]] && source $GRUVBOX
