#!/usr/bin/env bash
_zsh_path="$(which zsh)"

# set default shell if it's not already done
if [[ $SHELL =~ zsh ]]; then
  echo "You are already running a zsh shell, Good for you!"
else
  echo "It's time to change your default shell to $_shell..."
  chsh -s "${_zsh_path}" "$(whoami)"
  echo "Reloading shell to apply changes..."
  exec $_zsh_path -l
fi
