#!/usr/bin/env zsh
# This file is sourced by all instances of Zsh, and thus, it should be kept as
# small as possible and should only define environment variables.
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export EDITOR="vim"
export VISUAL="$EDITOR"
export PAGER="less"
export GOPATH="$HOME/dev/go"

# Language
if [[ -z "$LANG" ]]; then
  export LANG="en_US.UTF-8"
fi

if [[ -z "$TMUX" ]]; then
  export TERM="xterm-256color"
else
  export TERM="screen-256color"
fi

# Paths
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  "$HOME/.dotfiles/bin"
  "$HOME/bin"
  "$GOPATH/bin"
  "/usr/local/opt/go/libexec/bin"
  "$HOME/.cabal/bin" # Haskell libraries
  "$path[@]"
)

# Less

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
