#!/usr/bin/env bash

basedeps=(git)
deps=(emacs)
brew_deps=("emacs --with-modules --with-librsvg --with-imagemagick@6 --with-gnutls --with-cocoa")

install-deps

if [[ ! -d "$HOME/.emacs.d" ]]; then
  git clone --recursive "https://github.com/hlissner/.emacs.d" "$HOME/.emacs.d"
fi
