#!/usr/bin/env bash

basedeps=(
  git
  ag
)
deps=(
  emacs
)
brew_deps=(
  cmake
  llvm
  "emacs --with-modules --with-librsvg --with-imagemagick@6 --with-gnutls --with-cocoa"
)

dots install fonts
dots install editorconfig
install-deps

emacsd="$HOME/.emacs.d"
if [[ ! -d "$HOME/.emacs.d" ]]; then
  # git clone --recursive --branch develop "https://github.com/hlissner/.emacs.d" "$emacsd"
  git clone --recursive --branch develop "https://github.com/eduarbo/doom-emacs" "$emacsd"
fi

stow-module

pushd "$emacsd" >/dev/null
YES=1 make install && make compile
popd >/dev/null

_info "Don't forget to install the fonts included with all-the-icons with: M-x all-the-icons-install-fonts"
