#!/usr/bin/env bash

brew_deps=(hammerspoon)

install-deps

defaults write org.hammerspoon.Hammerspoon '{
    MJShowDockIconKey = 0;
    MJShowMenuIconKey = 0;
    MJSkipDockMenuIconProblemAlertKey = 1;
}'
