#!/usr/bin/env bash

# Setup -------------------------------------------------------------------- {{{
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  _colorflag="--color"
else # OS X `ls`
  _colorflag="-G"
fi

# Allow aliases to be with sudo
alias sudo="sudo "

### Get os name via uname ###
_myos="$(uname)"
# }}}
# Linux aliases ------------------------------------------------------------ {{{
if [ $_myos = "Linux" ]; then
  ##########################
  # Linux-specific aliases #
  ##########################

  alias open="xdg-open"
  alias o="xdg-open"
  alias oo="xdg-open ."

  alias update="sudo apt-get update"
  alias install="sudo apt-get install"
  alias remove="sudo apt-get remove"

fi
# }}}
# OSX aliases -------------------------------------------------------------- {{{
if [ "$_myos" = "Darwin" ]; then
  ########################
  # OSX-specific aliases #
  ########################

  alias open="open"
  alias o="open"
  alias oo="open ."

  # Empty the Trash on all mounted volumes and the main HDD
  # Also, clear Apple’s System Logs to improve shell startup speed
  alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

  # JavaScriptCore REPL
  _jscbin="/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc";
  [ -e "${_jscbin}" ] && alias jsc="${_jscbin}";
  unset _jscbin;

  # Merge PDF files
  # Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
  _joinpy='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
  [ -e "${_joinpy}" ] && alias mergepdf="${_joinpy}";

  # Google translate cli aliases
  alias trse="trs {=es}"
  alias trsf="trs {=fr}"

  # Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
  alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update'

  # Recursively delete `.DS_Store` files
  alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

  # Lock the screen (when going AFK)
  alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

  alias b="brew"
  alias c="brew cask"

fi
# }}}
# Shortcuts ---------------------------------------------------------------- {{{
unset _myos;

alias scp='rsync --rsh=ssh -CarvP'
alias top='top -o cpu'

alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dev='cd ~/dev'

alias ec='vim ~/.editorconfig'
alias ed='vim ~/.vim/custom-dictionary.utf-8.add'
alias ef='vim ~/.config/fish/config.fish'
alias eg='vim ~/.gitconfig'
alias ej='vim ~/.jshintrc'
alias et='vim ~/.tmux.conf'
alias ev='vim ~/.dotfiles/vimrc'
alias todo="vim ~/todo.md"
alias etp="vim ~/tp.md"
alias e='emacsclient -t'
alias ec='emacsclient -c'

alias r='rails'
alias rg='rails g'
alias rn='rails new'
alias rs='rails s'
alias rc='rails c'

alias v='mvim'
alias V='mvim .'

alias tm="tmux -u2"
alias tmkillall="tmux ls | grep : | cut -d. -f1 | awk '{print substr($1, 0, length($1)-1)}' | xargs -n1 tmux kill-session -t"
alias cl="clear"

alias fa='fasd -a'        # any
alias fs='fasd -si'       # show / search / select
alias fd='fasd -d'        # directory
alias f='fasd -f'         # file
alias fsd='fasd -sid'     # interactive directory selection
alias fsf='fasd -sif'     # interactive file selection
alias j='fasd_cd -d'      # cd, same functionality as j in autojump
alias jj='fasd_cd -d -i'  # cd with interactive selection

alias d='docker'

# Reload the sell and return the load time
alias loadtime="/usr/bin/time $SHELL -i -c exit"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Lists the ten most used commands.
alias historystat="history 0 | awk '{print \$2}' | sort | uniq -c | sort -n -r | head"

alias py="python"
# }}}
# Files & Directories ------------------------------------------------------ {{{
alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias l="ls -l ${_colorflag}" # List all files colorized in long format
alias la="ls -lA ${_colorflag}" # List all files colorized in long format, including dot files
alias lsd='ls -l ${_colorflag} | grep "^d"' # List only directories
alias ls="command ls -h ${_colorflag}"
alias lt='ls -ltr'
unset _colorflag;

alias md='mkdir -p'
alias rd='rmdir'
alias RM='rm -vrf'

duh() { # disk usage for humans
  test $# -eq 0 && set -- *
  du -sch "$@" | sort -h
}

bam() { # backup with move
  for file; do
    mv -v $file{,.bak}
  done
}

bum() { # undo backup move
  for file; do
    mv -v "$file" "${file%.bak}"
  done
}

bac() { # backup with copy
  for file; do
    cp -Rpv "$file" "$file~$(date -Ins)~"
  done
}

buc() { # undo backup copy
  for file; do
    dest=${file%%\~*}
    test -d "$dest" && mv -v "$dest" "$file.orig"
    mv -v "$file" "$dest"
  done
}

mount-dir-ro() {
sudo mount --bind "$@" &&
  sudo mount -o remount,ro,bind "$@"
}
# }}}
# Taskwarrior -------------------------------------------------------------- {{{
alias t="task"
alias ta="task add"
# }}}
# Git ---------------------------------------------------------------------- {{{
alias g='git'
alias gs='git status'
alias ga='git add'
alias gt='git tag -n'                       # show tags with <n> lines of each tag message

alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit -am'

alias gco='git checkout'                    # checkout
alias gnb='git checkout -b'                 # create and switch to a new branch (mnemonic: "git new branch branchname...")

alias gd='git diff'                         # diff unstaged changes
alias gdt='git difftool'                    # Git difftool
alias gdc='git diff --cached'               # diff staged changes

alias gl="git log --color --date=short --pretty=format:'%C(auto)%h %Cgreen%cD %C(cyan)%cr %Cblue[%cn]%C(auto)%d%n%Creset%B'"
alias glg="git log --color --graph --date=short --pretty=format:'%C(auto)%h %Cgreen%cD %C(cyan)%cr %Cblue[%cn]%C(auto)%d%n%Creset%B'"
alias gll="git log --color --date=short --pretty=format:'%C(auto)%h %Cgreen%cr %Cblue[%cn]%C(auto) %d%Creset%s'"
alias glm='git log --color --author="$(git config user.name)" --pretty=format:"%C(auto)%h %Cgreen%cr%Creset %s" --date=short'

alias gb='git branch'
alias gbb='git branch -v'
alias gm='git merge'
alias gf='git fetch'
alias gps='git push'
alias gpl='git pull'
alias grc='git rebase --continue'
alias grs='git rebase --skip'
alias gmt='git mergetool'                   # fire up the merge tool
alias gfl='git log -u'                      # show changes to a file

alias gg='git grep --break --heading --line-number'
alias ggi='git grep -ni'

# stash
alias gss='git stash'                       # stash changes
alias gsa='git stash apply'                 # apply stash
alias gsl='git stash list'                  # list stashes
alias gsp='git stash pop'                   # pop stash
alias gsd='git stash drop'                  # drop stashes

alias gcp='git cherry-pick -x'              # grab a change from a branch

# setopt nocompletealiases      # treat `gco` like `git checkout`
# compdef _git tig=git-checkout # treat `tig` like `git checkout`
# compdef hub=git               # treat `hub` like `git`
# }}}
# Misc --------------------------------------------------------------------- {{{
alias server='python -m SimpleHTTPServer'

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

alias whois="whois -h whois-servers.net"

# Copy my public key to my clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"
# }}}
