#!bin/bash
# Prompt

BGBLACK="\[\033[40m\]"
BGRED="\[\033[41m\]"
BGGREEN="\[\033[42m\]"
BGYELLOW="\[\033[43m\]"
BGBLUE="\[\033[44m\]"
BGMAGENTA="\[\033[45m\]"
BGCYAN="\[\033[46m\]"
BGWHITE="\[\033[47m\]"
BGTRANS="\[\033[49m\]"

BLACK="\[\033[30m\]"
RED="\[\033[31m\]"
GREEN="\[\033[32m\]"
YELLOW="\[\033[33m\]"
BLUE="\[\033[34m\]"
MAGENTA="\[\033[35m\]"
CYAN="\[\033[36m\]"
WHITE="\[\033[37m\]"
TRANS="\[\033[39m\]"

BOLD="\[\033[1m\]"
RESET="\[\033[0m\]"

BRANCH="\$(git branch 2>/dev/null | grep -e '\*' | sed 's/^..\(.*\)/\\[ ⭠ \\]\1/')"

export PS1="\n${YELLOW}${BOLD}⚡ \
${GREEN}\w\
${CYAN}${BRANCH}\
${YELLOW} $ ${RESET}"

export PS2="${BOLD}${YELLOW}❯ ${RESET}"
